services:
  - type: web
    name: rag-agent-streamlit
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main.py --server.port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: GROQ_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
